/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import config.Session;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import restaurantbook.LoginForm;



/**
 *
 * @author milan
 */
public class Bookingfilllup extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Bookingfilllup
     */
    public Bookingfilllup(int tableId, String tableNumber, int capacity, String status, int userId) {
        initComponents();
       // Fill fields or handle data here
        txtTableID.setText(String.valueOf(tableId));
        txtTableNumber.setText(tableNumber);
        txtCapacity.setText(String.valueOf(capacity));
        txtTableStatus.setText(status);
        txtUserID.setText(String.valueOf(userId));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTableID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTableNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTableStatus = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtTableID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        jLabel1.setText("Table ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel1.add(txtTableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 30));

        jLabel2.setText("Table Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel3.setText("Capacity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 30));

        jLabel4.setText("Table Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        jPanel1.add(txtTableStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 30));
        jPanel1.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        jPanel1.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 30));

        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        jPanel1.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 30));

        jLabel7.setText("User ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
                                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  int tableId = Integer.parseInt(txtTableID.getText());
int userId = Integer.parseInt(txtUserID.getText());
String tableStatus = txtTableStatus.getText();
String fname = txtFname.getText().trim();
String lname = txtLname.getText().trim();

// Check if table is available
if (!tableStatus.equalsIgnoreCase("available")) {
    JOptionPane.showMessageDialog(this, "Table is not available for booking.");
    return;
}

// Check if names are not empty
if (fname.isEmpty() || lname.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter your first and last name.");
    return;
}

try {
    Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/restaurantbooking_db", "root", "");

    // Insert booking
    String sql = "INSERT INTO bookings (table_id, user_id, u_fname, u_lname, status, booking_time) " +
                 "VALUES (?, ?, ?, ?, ?, NOW())";
    PreparedStatement stmt = conn.prepareStatement(sql);
    stmt.setInt(1, tableId);
    stmt.setInt(2, userId);
    stmt.setString(3, fname);
    stmt.setString(4, lname);
    stmt.setString(5, "pending");

    stmt.executeUpdate();

    // Update table status to 'booked'
    String updateTableSql = "UPDATE tables SET status = 'booked' WHERE table_id = ?";
    PreparedStatement updateStmt = conn.prepareStatement(updateTableSql);
    updateStmt.setInt(1, tableId);
    updateStmt.executeUpdate();

    conn.close();

    JOptionPane.showMessageDialog(this, "Booking submitted successfully!");
    this.dispose(); // Close the form

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error submitting booking.");
}
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookingfilllup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookingfilllup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookingfilllup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookingfilllup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookingfilllup(1, "T01", 4, "Available", 101).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtTableID;
    private javax.swing.JTextField txtTableNumber;
    private javax.swing.JTextField txtTableStatus;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
